Django1.02/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp


urlpatterns = [
    path('', mainapp.main),
    path('products/', mainapp.products),
    path('contact/', mainapp.contact),
    path('admin/', admin.site.urls),
]

authapp/urls.py
from django.urls import path
from django.templatetags.static import static
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
#from django.templatetags.static import static


urlpatterns = [
    path('', mainapp.index ,name='index'),
    #path('', mainapp.main,name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('products/', mainapp.products,name='products'),
    path('contacts/', mainapp.contacts,name='contacts'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

def products(request, pk=None):
    print(pk)

mainapp/urls.py
from django.urls import path

from django.urls import include

import mainapp.views as mainapp

app_name = 'mainapp'


def products(request, pk=None):
    print(pk)

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='category'),
    path('auth/', include('authapp.urls', namespace='auth')),
]

authapp/models.py
from django.db import models

from django.db import models

from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name = 'возраст')

mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

def __str__(self):
    return self.name



class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта',
    max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8,
    decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе',
    default=0)

def __str__(self):
    return f"{self.name} ({self.category.name})"


### twetetwe

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm

from .models import ShopUser

class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

Django1.02/geekshop/mainapp/views.py
from django.shortcuts import render

# Create your views here.


def main(request):
    return render(request, 'mainapp/index.html')


def products(request):
    return render(request, 'mainapp/products.html')


def contact(request):
    return render(request, 'mainapp/contact.html')

authapp/views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm
from django.contrib import auth
from django.urls import reverse
from django.templatetags.static import static


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/base.html', content)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))

mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product
from django.templatetags.static import static

# Create your views here.

def main(request):
    title = 'главная'
    products = Product.objects.all()[:4]
    content = {'title': title, 'products': products}
    return render(request, 'mainapp/index.html', content)

def index(request):
    products = Product.objects.all()[:2]
    list_params = {'no': 'Vau,',
                   'p1': True,
                    'info': False
                   };

    #context = render(request, 'mainapp/index.html', context = list_params)

    context = {
        'title' : 'главная',
        'product' : 'products',
    }

    return render(request,'mainapp/index.html', context)
    #return context
    #context = render(request, 'mainapp/index.html', context=list_params)



#def main(request):
#    return render(request, 'mainapp/index.html')


def products(request):
    links_menu = [
        {'href': '', 'name': 'все'},
        {'href': '', 'name': 'дом'},
        {'href': '', 'name': 'офис'},
        {'href': '', 'name': 'модерн'},
        {'href': '', 'name': 'классика'}
    ]

    context =  {
        'title' : 'каталог',
        'links_menu' : links_menu,
        'object' : 'Product.objects.get(id = 1)'
    }


    return render(request,'mainapp/products.html',context=context)


def contacts(request):
    return render(request, 'mainapp/contacts.html')

Django1.02/geekshop/mainapp/templates/mainapp/contact.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Контакты</title>
	<link rel="stylesheet" type="text/css" href="/static/geekshop/style.css">
	<link rel="stylesheet" href="fonts/font-awesome/css/font-awesome.css">
	<img src="/static/img/arrow.png" alt="arrow">
</head>
<body>
	<div class="container">
		<div class="hero">
			<div class="header clearfix">
				<a href="/" class="logo"></a>
				<ul class="menu">
					<li><a href="/">домой</a></li>
					<li><a href="products.html">продукты</a></li>
					<li><a href="contact.html" class="active">контакты</a></li>
				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

</body>
</html>

Django1.02/geekshop/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Магазин</title>
	<link rel="stylesheet" type="text/css" href="static/geekshop/style.css">
	<link rel="stylesheet" href="fonts/font-awesome/css/font-awesome.css">
	<img src="/static/img/arrow.png" alt="arrow">
</head>
<body>
	<div class="container">
		<div class="slider">
			<div class="header clearfix">
				<a href="/" class="logo"></a>
				<ul class="menu">
					<li><a href="/" class="active">домой</a></li>
					<li><a href="products/">продукты</a></li>
					<li><a href="contacts/">контакты</a></li>
				</ul>
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="img/arrow.png" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="img/arrow.png" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				<div class="block">
					<a href="#"><img src="static/geekshop/img/product-1.jpg" alt="">
						<div class="text">
							<img src="static/geekshop/img/icon-hover.png" alt="img">
							<h4>Отличный стул</h4>
							<p>Расположитесь комфортно. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="static/geekshop/img/product-2.jpg" alt="">
						<div class="text">
							<img src="static/geekshop/img/icon-hover.png" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

</body>
</html>

Django1.02/geekshop/mainapp/templates/mainapp/products.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Каталог</title>
	<link rel="stylesheet" type="text/css" href="/static/geekshop/style.css">
	<link rel="stylesheet" href="fonts/font-awesome/css/font-awesome.css">
	<img src="/static/img/arrow.png" alt="arrow">
</head>
<body>
	<div class="container">
		<div class="hero-white">
			<div class="header clearfix">
				<a href="/" class="logo"></a>
				<ul class="menu">
					<li><a href="/">домой</a></li>
					<li><a href="products.html" class="active">продукты</a></li>
					<li><a href="contact.html">контакты</a></li>

				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
		</div>

		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
					<li><a href="#" class="active">все</a></li>
					<li><a href="#">дом</a></li>
					<li><a href="#">офис</a></li>
					<li><a href="#">модерн</a></li>
					<li><a href="#">классика</a></li>
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="img/slider1.jpg">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="img/controll.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="img/controll1.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="img/controll2.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p>
						<p>Отличное качество материалов
						позволит вам это.</p>
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="img/product-11.jpg" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="img/product-21.jpg" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="img/product-31.jpg" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>

	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

</body>
</html>

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
     {% block title %}
        {{ title|title }}
     {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
    <div class="container">
     <div class="login">
        <div class="h2 text-center head">
            Вход в систему
        </div>

        {% block content %}
        {% endblock %}
     </div>
    </div>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>

{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{{title|title}}</title>
	<!--<link rel="stylesheet" type="text/css" href="static/geekshop/style.css">-->
	<link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">
	<link rel="stylesheet" href="fonts/font-awesome/css/font-awesome.css">
	<img src="/static/img/arrow.png" alt="arrow">
</head>

<body>
      {% block ru1 %}

     {% endblock %}
	{% block ru %}

     {% endblock %}

	<div class="container">
        {% block content %}

        {% endblock %}

		<div class="clr"></div>

	</div>



</body>
</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html'%}

{% load static %}



	{% block content %}
	<div class="container">

		<div class="hero">
			{% include 'mainapp/includes/header.html' %}
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
	{% endblock %}

{% block ru1 %}
   hello, Tomas!!!
{% endblock %}

mainapp/templates/mainapp/inc_menu.html
{% if user.is_authenticated %}
<li>
    <a href="{% url 'auth:edit' %}">
        {{ user.first_name|default:'Пользователь' }}
    </a>
</li>
{% endif %}
<li>
    {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">выйти</a>
    {% else %}
    <a href="{% url 'auth:login' %}">войти</a>
    {% endif %}
</li>

mainapp/templates/mainapp/includes/header.html
{% load static %}


<div class="header clearfix">
				<!--<a href="/" class="logo"></a>-->
				<a href="{% url 'index' %}" class="logo"></a>
				<ul class="menu">
					<!--<li><a href="/">домой</a></li>-->
					<li><a href="{% url 'index' %}">домой</a></li>
					<!--<li><a href="products.html">продукты</a></li>
					<li><a href="contact.html" class="active">контакты</a></li>-->
					<!--<li><a href="{% url 'products' %}" class="active">продукты</a></li>
					<li><a href="{% url 'contacts' %}" class="active">контакты</a></li>-->
					<li><a href="{% url 'products' %}" >продукты</a></li>
					<li><a href="{% url 'contacts' %}" >контакты</a></li>
				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
</div>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html'%}

{% load static %}

{% block content %}

	<div class="container">
		<div class="slider">
			{% include 'mainapp/includes/header.html' %}
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> {{ no }} удобные стулья</h3>
				{% if  p1 %}
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				{% endif %}
				<a href="#" class="button-order">заказать <img src="img/arrow.png" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="img/arrow.png" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for product in products %}
					<div class="block">
					<a href="#"><img src="/media/{{products_images}}" alt="">
						<div class="text">
							<img src="static/geekshop/img/icon-hover.png" alt="img">
							<h4>{{ product.name }}/h4>
							<p>{{ product.short_desc }} </p>
						</div>
					</a>
					</div>
				{% endfor %}
			</div>
		</div>

		<div class="clr"></div>

	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

{% endblock %}

{% for product in products %}
	<div class="block">
		<a href="#">
			<img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
			<div class="text">
				<h3>{{ product.category.name }}</h3>
				<h4>{{ product.name }}</h4>
				<p>{{ product.description }}</p>
			</div>
		</a>
	</div>
{% endfor %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html'%}

{% load static %}



	{% block content %}
	<div class="container">
		<div class="hero-white">
			{% include 'mainapp/includes/header.html' %}
		</div>

		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
					{{ request.resolver_match.url_name }}
					{% for link in links_menu %}
						<li><a href="/{{ link.href }}/" class="active">{{link.name}}</a></li>
					{% endfor %}
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<!--<div class="slider-product">-->
					<div>
						<!--<img src="img/slider.jpg">-->
						<img src="static/img/google-play.png" alt="arrow1">
						<img src="static/img/app-store.png" alt="arrow2">
						<img src="static/img/social-links.png" alt="arrow3">
						<!--<img src="static/img/pear-1586866_1280.jpg" alt="arrow">-->
						<!--arrow.png-->
						<img src="static/img/arrow.png" alt="arrow4">
					</div>
					<div class="slider-control">
						<div class="block">
							<!--<a href="#"><img src="img/controll.jpg" alt="">-->
							<a href="#"><img src="img/google-play.png" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="img/controll1.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="img/controll2.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p>
						<p>Отличное качество материалов
						позволит вам это.</p>
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="img/product-11.jpg" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="img/product-21.jpg" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="img/product-31.jpg" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>

	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

{% endblock %}

{% block ru %}
   hello,World!!!
{% endblock %}